notification.kafka.bootstrap-servers=localhost:29092
notification.kafka.metrics-topic=orders-validation-metrics
notification.kafka.daily-report-topic=daily_report
notification.kafka.group-id=scala-notification-service

notification.alert.error-rate-percent=5.0
notification.alert.min-total=1
notification.alert.cooldown-seconds=30

notification.email.enabled=true
notification.email.from=scalapark68@gmail.com
notification.email.to=anderson.fgn13@gmail.com
notification.email.sendgrid.api-key=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
