consumer {
  bootstrap-servers = ${?KAFKA_BOOTSTRAP_SERVERS}
  group-id = "scala-streaming-orders-consumer"
  auto-offset-reset = "earliest"
  enable-auto-commit = false
  key-deserializer = "org.apache.kafka.common.serialization.StringDeserializer"
  value-deserializer = "org.apache.kafka.common.serialization.StringDeserializer"
}

producer {
  bootstrap-servers = ${?KAFKA_BOOTSTRAP_SERVERS}
  key-serializer = "org.apache.kafka.common.serialization.StringSerializer"
  value-serializer = "org.apache.kafka.common.serialization.StringSerializer"
}

topics {
  input = "orders"
  validated-output = "orders-validated"
  metrics-output = "orders-validation-metrics"
}

metrics {
  publish-interval-seconds = 30
}

spark {
  app-name = "OrderSparkStreamingJob"
  master = "local[*]"
  checkpoint-base-path = "/tmp/pfsd-spark-checkpoints"
  trigger-processing-time = "10 seconds"
}

mongo {
  uri = ${?MONGO_URI}
  database = ${?DATABASE_NAME}
  collection = ${?COLLECTION_NAME}
  metrics-collection = ${?COLLECTION_METRICS}
}
