dashboard.kafka {
  bootstrap-servers = "localhost:29092"
  bootstrap-servers = ${?KAFKA_BOOTSTRAP_SERVERS}
  metrics-topic = "orders-validation-metrics"
  metrics-topic = ${?METRICS_TOPIC}
  daily-report-topic = "daily_report"
  daily-report-topic = ${?DAILY_REPORT_TOPIC}
  validated-orders-topic = "orders-validated"
  validated-orders-topic = ${?VALIDATED_ORDERS_TOPIC}
  group-id = "scala-dashboard-api"
  group-id = ${?DASHBOARD_GROUP_ID}
}
