play {
  http {
    secret.key = "scala-api-dev-secret-change-in-prod"
    secret.key = ${?APPLICATION_SECRET}
  }
}

pekko {
  loglevel = "INFO"
}

logger {
  application = "INFO"
}

include "kafka-intro.conf"
